import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logo from "../assets/barangay-logo.png";

export function generatePdf(title, columns, rows, print = false) {
    const doc = new jsPDF();


    const fullName =
        localStorage.getItem("fullName") || "Administrator";

    const role =
        localStorage.getItem("role") === "Admin"
            ? "System Administrator"
            : "Barangay Staff";

    // ==========================
    // HEADER
    // ==========================

    doc.addImage(logo, "PNG", 15, 10, 25, 25);

    doc.setFont("helvetica", "bold");

    doc.setFontSize(14);
    doc.text("REPUBLIC OF THE PHILIPPINES", 105, 15, {
        align: "center"
    });

    doc.setFontSize(11);
    doc.text("Region IX - Zamboanga Peninsula", 105, 22, {
        align: "center"
    });

    doc.text("City of Dipolog", 105, 28, {
        align: "center"
    });

    doc.text("Barangay Sta. Isabel", 105, 34, {
        align: "center"
    });

    doc.setFontSize(15);
    doc.text("BARANGAY EQUIPMENT BORROWING SYSTEM", 105, 44, {
        align: "center"
    });

    doc.setFontSize(13);
    doc.text(title.toUpperCase(), 105, 52, {
        align: "center"
    });

    // ==========================
    // REPORT DETAILS
    // ==========================

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    doc.text(`Generated By : ${fullName}`, 14, 63);
    doc.text(`Role          : ${role}`, 14, 69);
    doc.text(
        `Date Generated: ${new Date().toLocaleString()}`,
        14,
        75
    );

    // ==========================
    // TABLE
    // ==========================

    autoTable(doc, {
        startY: 85,

        head: [columns],

        body: rows,

        theme: "grid",

        headStyles: {
            fillColor: [8, 40, 74],
            textColor: 255,
            fontStyle: "bold"
        },

        styles: {
            fontSize: 9,
            cellPadding: 3
        }
    });

    const pageCount = doc.getNumberOfPages();

for (let i = 1; i <= pageCount; i++) {

    doc.setPage(i);

    doc.setFontSize(9);

    doc.text(
        `Page ${i} of ${pageCount}`,
        105,
        290,
        { align: "center" }
    );

}

   // ==========================
// SIGNATURE
// ==========================

const finalY = doc.lastAutoTable.finalY + 20;

doc.setFont("helvetica", "normal");
doc.setFontSize(10);

doc.text("Prepared by:", 140, finalY);

doc.line(140, finalY + 20, 195, finalY + 20);

doc.setFont("helvetica", "bold");
doc.text(fullName.toUpperCase(), 167.5, finalY + 26, {
    align: "center"
});

doc.setFont("helvetica", "normal");
doc.text(role, 167.5, finalY + 32, {
    align: "center"
});

if (print) {

    const pdfBlob = doc.output("blob");

    const pdfUrl = URL.createObjectURL(pdfBlob);

    const printWindow = window.open(pdfUrl);

    printWindow.onload = () => {
        printWindow.print();
    };

}
else {

    doc.save(`${title}.pdf`);

}
}