import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import seal from "../assets/seal.png";

export function generatePdf(title, columns, rows, print = false) {
    const doc = new jsPDF();

    const fullName =
        localStorage.getItem("fullName") || "Administrator";

    const role =
        localStorage.getItem("role") === "Admin"
            ? "System Administrator"
            : "Barangay Staff";

    const currentDate = new Date().toLocaleString();

    const reportNo =
    `BR-${new Date().getFullYear()}-${Date.now().toString().slice(-4)}`;

    // =====================================================
    // HEADER
    // =====================================================

    doc.addImage(seal, "PNG", 80, 20, 50, 50);

    doc.setFont("helvetica", "bold");

    doc.setFontSize(13);
    doc.text("REPUBLIC OF THE PHILIPPINES",105,64,{
        align: "center",
    });

    doc.setFontSize(11);
    doc.text("City of Dipolog",105,70,{
        align: "center",
    });

    doc.text("Barangay Sta. Filomena",105,76,{
        align: "center",
    });

    doc.setFontSize(16);
    doc.text("BARANGAY EQUIPMENT BORROWING",105,86,{
        align: "center",
    });

    doc.text("AND MONITORING SYSTEM",105,93,{
        align: "center",
    });

    doc.setDrawColor(20, 33, 61);
    doc.setLineWidth(0.6);
    doc.line(30,98,180,98);

    doc.setFontSize(13);
    doc.text(title.toUpperCase(),105,106,{
        align: "center",
    });

    doc.setFontSize(10);
doc.setFont("helvetica","normal");

doc.text(
    `Report No.: ${reportNo}`,
    105,
    112,
    {align:"center"}
);

    // =====================================================
    // REPORT INFORMATION
    // =====================================================

    doc.setDrawColor(180);
    doc.setFillColor(248, 248, 248);

    doc.roundedRect(14,114,182,28,2,2,"FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);

    doc.text("Generated By", 20, 123);
    doc.text("Role", 20, 130);
    doc.text("Date Generated", 20, 137);

    doc.setFont("helvetica", "normal");

    doc.text(fullName, 65, 123);
    doc.text(role, 65, 130);
    doc.text(currentDate, 65, 137);

    // =====================================================
    // TABLE
    // =====================================================

    autoTable(doc, {
        startY:150,

        head: [columns],

        body: rows,

        theme: "striped",

        headStyles:{
    fillColor:[20,33,61],
    textColor:255,
    fontStyle:"bold",
    halign:"center",
    valign:"middle",
    minCellHeight:12,
    fontSize:10
},

        styles: {
            fontSize: 9,
            cellPadding: 5,
            lineColor: [220, 220, 220],
            lineWidth: 0.2,
        },

        bodyStyles: {
            halign: "center",
        },

        alternateRowStyles: {
            fillColor: [248, 249, 250],
        },
    });

    // =====================================================
    // SIGNATURE
    // =====================================================

    let finalY = doc.lastAutoTable.finalY + 12;

    // Prevent signature from being cut off
    if (finalY > 245) {
        doc.addPage();
        finalY = 40;
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    doc.text("Prepared by:",140,finalY);

    doc.line(140,finalY+20,195,finalY+20);

    doc.setFont("helvetica", "bold");

    doc.text(
        fullName.toUpperCase(),
        167.5,
        finalY + 27,
        {
            align: "center",
        }
    );

    doc.setFont("helvetica", "normal");

    doc.text(
        role,
        167.5,
        finalY + 33,
        {
            align: "center",
        }
    );

    // =====================================================
    // FOOTER
    // =====================================================

    const pageCount = doc.getNumberOfPages();

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);

        doc.setDrawColor(180);
        doc.line(14, 285, 196, 285);

        doc.setFontSize(8);

        doc.text(
            "Barangay Equipment Borrowing and Monitoring System",
            14,
            289
        );

        doc.text(
            `Page ${i} of ${pageCount}`,
            196,
            289,
            {
                align: "right",
            }
        );
    }

    // =====================================================
    // EXPORT / PRINT
    // =====================================================

    if (print) {
        const pdfBlob = doc.output("blob");
        const pdfUrl = URL.createObjectURL(pdfBlob);

        const printWindow = window.open(pdfUrl);

        printWindow.onload = () => {
            printWindow.print();
        };
    } else {
        doc.save(`${title}.pdf`);
    }
}